language: node_js
nodejs:
  - "8"
  - "10"
env:
  - DB_TEST=true
before_install:
  - npm install -g mocha@5.2.x
  - npm install -g nyc@13.0.x
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
