sudo: required
language: node_js
nodejs:
  - "8"
  - "10"
services:
  - docker
before_install:
  - sudo /etc/init.d/mysql stop
install:
  - npm run docker:install
  - npm run docker:start
cache:
  directories:
    - "node_modules"
