sudo: required
dist: xenial
language: node_js
nodejs:
  - "8"
  - "10"
env:
  - DB_TEST=true
before_install:
  - sudo apt-get install -y build-essential python2.7
  - npm install -g node-gyp mocha@5.2.x nyc@13.0.x
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
