os: linux
sudo: required
language: node_js
node_js: 8.11.4
env:
  - NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openssl
before_install:
  - npm install -g mocha@5.2.x nyc@13.0.x
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
