sudo: required
dist: xenial
addons:
  apt:
    packages:
      - make
      - g++-5
      - gcc-5
language: node_js
nodejs:
  - "8"
  - "10"
env:
  - DB_TEST=true
before_install:
  - npm install -g mocha@5.2.x nyc@13.0.x node-pre-gyp
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
