os: linux
sudo: required
language: node_js
node_js: 8.11.4
env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - python2.7
      - openssl
before_install:
  - npm install -g mocha@5.2.x nyc@13.0.x sequelize-cli@4.1.x
  - sequelize db:seed:all
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
